name: Build Docker

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install NBGV
        run: dotnet tool install --tool-path . nbgv

      - name: Get NBGV Version
        id: nbgv-version
        run: |
          c_version=$(nbgv get-version -v SimpleVersion)
          a_version=$(nbgv get-version -v AssemblyInformationalVersion)
          echo "package version = ${c_version}"
          echo "information version = ${a_version}"
          echo "C_VERSION=${c_version}" >> "$GITHUB_OUTPUT"
          echo "export default \"${a_version}\" as string;" > ./UI/src/version.ts

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build NodeJS
        working-directory: ./UI
        run: |
          npm install
          npm run build
          cp -r ./dist ../Server/wwwroot

      - name: .NET Publish
        env:
          ESCAPED_TAGS: '''"${{ steps.nbgv-version.outputs.C_VERSION }};latest"'''
        run: dotnet publish Server/Webber.Server.csproj --os linux --arch x64 -c Release -p:ContainerImageTags=${{ env.ESCAPED_TAGS }} -p:ContainerRegistry=ghcr.io -p:ContainerRepository=${{ github.repository }} -p:PublishProfile=DefaultContainer
